image: python:3.7.0-stretch

run pylint:
  stage: test
  script:    
    - pip install -r requirements.txt
    - pip install -e .
    - python tests/run_pylint.py

create docs page:
  stage: deploy
  script:    
    - pip install -r requirements.txt
    - pip install -e .
    - make html -C docs
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - tags

publish to pypi:
  stage: deploy
  script:    
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  only:
    - tags
